### ISSUE TITLE
Look into setting a maximum password length to prevent DOS attacks

### ISSUE THREAD

**Issue by davidmurdoch** [davidmurdoch/easy-pbkdf2#6]
DOS attacks via long passwords will probably be making their rounds (again). http://www.tomsguide.com/us/django-long-password-security,news-17557.html

I'm thinking about setting a default max-length of maybe 4096 bytes. This max-password length would be configurable.

**Comment by aintabb** [comment]
I can grab this one if no one is working currently?

**Comment by davidmurdoch** [comment]
go for it!

**Comment by davidmurdoch** [comment]
I actually just noticed there is already a PR for this feature. I'm just going to merge that :-)

**Comment by aintabb** [comment]
@davidmurdoch Oh, I was so close to get a t-shirt. Thanks anyway :)

**Comment by davidmurdoch** [comment]
Ah, didn't realize it was for a hacktoberfest. If you are familiar with HTTP basic auth, you could try your hand at https://github.com/trufflesuite/ganache-core/issues/418

**Comment by aintabb** [comment]
@davidmurdoch I don't have experience with HTTP basic auth, but I think i can give it a shot. Do you have any resource that I can check or any starter guide for ganache-core project?
