### ISSUE TITLE
Change default number of iterations to much higher

### ISSUE THREAD

**Issue by davidmurdoch** [davidmurdoch/easy-pbkdf2#7]
The default of 512 is laughably low. Consider using 64,000 iterations, with automatic doubling every 2 years since 2012.

Apparently 64,000 iterations was recommended by OWASP in 2012, with the recommendation that this value double every 2 years. I couldn't find the source for this though, and I'll need to benchmark a bit to ensure I don't cause sites to DOS themselves in a few years.

**Comment by orand** [comment]
The [OWASP password storage cheat sheet](https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet) only gives an example of 10,000 which is used by Apple for iTunes passwords.

The source for the 64,000 figure appears to be [someone on StackOverflow](http://stackoverflow.com/a/14263775/71262) linking to the OWASP password storage cheat sheet.

**Comment by davidmurdoch** [comment]
Nice find! I used the way back machine and found the original reference to 64,000 iterations: https://web.archive.org/web/20121004065650/https://www.owasp.org/index.php/Password_Storage_Cheat_Sheet

> A minimum of 1000 operations was recommended in the RSA PKCS5 standard in 2000, a value that should be doubled every 2 years. Therefore, in 2012, it is recommended that 64,000 iterations be considered. You should measure the time required and make sure that its as large as possible without providing a significantly noticeable delay when your users authenticate.

Right now I'm not sure how I can safely update the default iterations without possibly DOSsing some servers that haven't tested for these higher iterations. Perhaps I can release a 1.1.2 that `console.warn`s about iterations lower than {some number}, with a warning that version 2.0.0 will automatically increase the default iterations of 512 to {some other number}. And then maybe next year I can release 2.0.0.

Thoughts and comments welcome!

**Comment by davidmurdoch** [comment]
done in the v2.0.0 branch
